DROP TABLE IF EXISTS dog CASCADE;

CREATE TABLE dogs (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INTEGER  NOT NULL DEFAULT 0,
    breed VARCHAR(255),
    adoption_fee INTEGER NOT NULL DEFAULT 0,
    admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
    description TEXT,
    photo_url VARCHAR(255) NOT NULL
);