DROP TABLE IF EXISTS listing CASCADE;

CREATE TABLE listings (
    id SERIAL PRIMARY KEY NOT NULL,
    publish_date DATE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    admin_id INTEGER REFERENCES admins(id) ON DELETE CASCADE,
    dog_id INTEGER REFERENCES dogs(id) ON DELETE CASCADE
);
